languageCode = "zh-CN"
title = "My New Hugo Site"
theme = "zhihu-zhuanlan"
enableEmoji = false
relativeURLs = true

[blackfriday]
  smartypants = false
  extensions = ["hardLineBreak"]
  fractions = false
  plainIDAnchors = true